#!/usr/bin/env python3
"""Root-owned local install, status and verified updates. Never controls Nginx."""
import fcntl
import hashlib
import json
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path
from urllib.parse import urlsplit

from release_verify import fetch_release, sha256, supported_host, validate_version, verify_manifest

ROOT = Path("/opt/exocortex/preza")
TRUST = Path("/etc/exocortex/release-trust/preza.pem")
GROUPS = (
    ("OPERATOR INPUT — edit only this section", ("PUBLIC_URL", "ACCESS_KEY", "LISTEN_PORT", "DATA_VOLUME")),
    ("GENERATED SECRETS — machine-owned", ("SESSION_SECRET", "ADMIN_KEY_HASH")),
    ("RELEASE LOCK — verified manifest, machine-owned", ("VERSION", "PREZA_IMAGE", "MANIFEST_SHA256")),
    ("RUNTIME DEFAULTS", ("PDF_RENDER_DPI", "MAX_UPLOAD_MB", "MAX_PDF_PAGES", "RENDER_TIMEOUT")),
)


def atomic_write(path, text, mode=0o600):
    path = Path(path)
    fd, temporary = tempfile.mkstemp(prefix="." + path.name + "-", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as out:
            out.write(text)
            out.flush()
            os.fsync(out.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def load_env(path):
    values = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "=" not in line:
            raise ValueError("Invalid .env line; use KEY=value or KEY=\"JSON string\"")
        key, value = line.split("=", 1)
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key) or key in values:
            raise ValueError("Invalid or duplicate .env key")
        if value.startswith('"'):
            value = json.loads(value)
            if not isinstance(value, str):
                raise ValueError(".env values must be strings")
        values[key] = value
    return values


def write_env(values):
    lines = ["# Generated by Preza. Values are literal; no shell expansion.",
             '# For spaces, quotes or newlines use a JSON string: ACCESS_KEY="my key".']
    for title, keys in GROUPS:
        lines.extend(("", "# === " + title + " ==="))
        lines.extend(key + "=" + json.dumps(values[key], ensure_ascii=False) for key in keys)
    atomic_write(ROOT / ".env", "\n".join(lines) + "\n")


def manifest(directory):
    directory = Path(directory)
    if TRUST.is_symlink() or TRUST.stat().st_uid != 0 or TRUST.stat().st_mode & 0o022:
        raise ValueError("Release trust file must be root-owned and protected from writes")
    raw = directory / "release.json"
    version = json.loads(raw.read_bytes())["version"]
    result = verify_manifest(raw, directory / "release.json.sig", TRUST, version)
    if (directory / ".release-digest").read_text().strip() != sha256(raw):
        raise ValueError("Installed release digest differs from verified manifest")
    return result


def release_locks(values, release, directory):
    return {**values, "VERSION": release["version"], "PREZA_IMAGE": release["image"],
            "MANIFEST_SHA256": sha256(Path(directory) / "release.json")}


def prepare():
    if (ROOT / ".env").exists():
        raise RuntimeError(".env already exists and was not overwritten")
    directory = ROOT / "current"
    release = manifest(directory)
    values = dict(PUBLIC_URL="https://preza.shmoza.net", ACCESS_KEY="", LISTEN_PORT="18480",
                  DATA_VOLUME="preza_presentation_data", SESSION_SECRET=secrets.token_urlsafe(48),
                  ADMIN_KEY_HASH="", PDF_RENDER_DPI="300", MAX_UPLOAD_MB="256",
                  MAX_PDF_PAGES="500", RENDER_TIMEOUT="300")
    write_env(release_locks(values, release, directory))


def validate_config(values, release, directory):
    expected = release_locks(values, release, directory)
    for key in ("VERSION", "PREZA_IMAGE", "MANIFEST_SHA256"):
        if values.get(key) != expected[key]:
            raise ValueError("Release locks must not be edited manually")
    # Access Key is exact opaque text; intentionally no strength/length/character policy.
    if values.get("ACCESS_KEY", "") == "":
        raise ValueError("Fill ACCESS_KEY in OPERATOR INPUT")
    url = urlsplit(values.get("PUBLIC_URL", ""))
    if (values["PUBLIC_URL"] != "https://preza.shmoza.net"
            or url.scheme != "https" or url.hostname != "preza.shmoza.net" or url.port not in (None, 443)
            or url.username or url.password or url.path or url.query or url.fragment):
        raise ValueError("PUBLIC_URL must be https://preza.shmoza.net")
    port = int(values["LISTEN_PORT"])
    if not 1024 <= port <= 65535 or port in (3000, 8080, 18180, 18184, 18280, 18380, 18381, 62050):
        raise ValueError("LISTEN_PORT is invalid or belongs to a protected host service")
    if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_.-]{0,127}", values.get("DATA_VOLUME", "")):
        raise ValueError("Invalid Docker DATA_VOLUME name")
    if not re.fullmatch(r"[A-Za-z0-9_-]{64}", values.get("SESSION_SECRET", "")):
        raise ValueError("Generated SESSION_SECRET is missing or changed")
    for key, low, high in (("PDF_RENDER_DPI", 72, 600), ("MAX_UPLOAD_MB", 1, 256),
                          ("MAX_PDF_PAGES", 1, 500), ("RENDER_TIMEOUT", 30, 300)):
        if not low <= int(values[key]) <= high:
            raise ValueError("Invalid runtime limit: " + key)


def run(command, **options):
    # Deployment values must come from our verified lock file, never shell overrides.
    environment = dict(os.environ)
    for key in ("PREZA_IMAGE", "PREZA_ROOT", "LISTEN_PORT", "DATA_VOLUME", "COMPOSE_FILE",
                "COMPOSE_PROJECT_NAME", "COMPOSE_PROFILES", "COMPOSE_ENV_FILES"):
        environment.pop(key, None)
    return subprocess.run(command, check=True, env=environment, **options)


def prerequisites():
    supported_host()
    for executable in ("docker", "curl", "openssl"):
        if not shutil.which(executable):
            raise RuntimeError("Install the prepared-server prerequisite: " + executable)
    run(["docker", "info"], stdout=subprocess.DEVNULL)
    version = run(["docker", "compose", "version", "--short"], capture_output=True, text=True).stdout.strip().lstrip("v")
    parts = tuple(map(int, re.match(r"(\d+)\.(\d+)", version).groups()))
    if parts < (2, 30):
        raise RuntimeError("Docker Compose 2.30+ is required")


def runtime_files(values):
    verifier = values.get("ADMIN_KEY_HASH", "")
    try:
        algorithm, iterations, salt, digest = verifier.split("$")
        if algorithm != "pbkdf2_sha256" or int(iterations) != 310000 or len(salt) != 32:
            raise ValueError("Invalid verifier")
        actual = hashlib.pbkdf2_hmac("sha256", values["ACCESS_KEY"].encode(), bytes.fromhex(salt), int(iterations)).hex()
        import hmac
        valid = algorithm == "pbkdf2_sha256" and int(iterations) == 310000 and hmac.compare_digest(actual, digest)
    except (ValueError, TypeError):
        valid = False
    if not valid:
        salt = secrets.token_hex(16)
        digest = hashlib.pbkdf2_hmac("sha256", values["ACCESS_KEY"].encode(), bytes.fromhex(salt), 310000).hex()
        values["ADMIN_KEY_HASH"] = "$".join(("pbkdf2_sha256", "310000", salt, digest))
        write_env(values)
    runtime = dict(DATA_DIR="/data", PUBLIC_URL=values["PUBLIC_URL"], SESSION_SECRET=values["SESSION_SECRET"],
                   ADMIN_KEY_HASH=values["ADMIN_KEY_HASH"],
                   **{key: values[key] for key in ("PDF_RENDER_DPI", "MAX_UPLOAD_MB", "MAX_PDF_PAGES", "RENDER_TIMEOUT")})
    atomic_write(ROOT / "runtime.env", "".join(key + "=" + value + "\n" for key, value in runtime.items()))
    locks = dict(PREZA_ROOT=str(ROOT), PREZA_IMAGE=values["PREZA_IMAGE"],
                 LISTEN_PORT=values["LISTEN_PORT"], DATA_VOLUME=values["DATA_VOLUME"])
    atomic_write(ROOT / "deployment.lock", "".join(key + "=" + value + "\n" for key, value in locks.items()))


def compose(directory, *arguments, **options):
    return run(["docker", "compose", "--project-name", "preza", "--env-file", str(ROOT / "deployment.lock"),
                "-f", str(Path(directory) / "compose.production.yml"), *arguments], **options)


def check_port(values):
    with socket.socket() as probe:
        try:
            probe.bind(("127.0.0.1", int(values["LISTEN_PORT"])))
        except OSError as exc:
            state = ROOT / "installed.json"
            if not state.exists():
                raise RuntimeError("Loopback port is already occupied") from exc
            previous = json.loads(state.read_text())
            if previous["port"] != values["LISTEN_PORT"] or previous["volume"] != values["DATA_VOLUME"]:
                raise RuntimeError("Loopback port conflicts with another service") from exc
            ids = compose(ROOT / "current", "ps", "-q", "api", capture_output=True, text=True).stdout.strip()
            if not ids:
                raise RuntimeError("Port is occupied by another process") from exc
            container = json.loads(run(["docker", "inspect", ids], capture_output=True, text=True).stdout)[0]
            bindings = container["HostConfig"]["PortBindings"].get("8000/tcp") or []
            if not container["State"]["Running"] or not any(item["HostIp"] == "127.0.0.1" and
                    item["HostPort"] == values["LISTEN_PORT"] for item in bindings):
                raise RuntimeError("Port is occupied by another process") from exc


def volume_command(values, code, *, backup=None, readonly=False, chown=False):
    command = ["docker", "run", "--rm", "--network", "none", "--read-only", "--user", "0",
               "--cap-drop", "ALL", "--cap-add", "DAC_OVERRIDE",
               "--security-opt", "no-new-privileges:true", "--memory", "256m", "--pids-limit", "64"]
    if chown:
        command.extend(("--cap-add", "CHOWN"))
    command.extend(("--mount", "type=volume,source=" + values["DATA_VOLUME"] + ",target=/data" +
                    (",readonly" if readonly else "")))
    if backup:
        command.extend(("--mount", "type=bind,source=" + str(backup) + ",target=/backup"))
    command.extend((values["PREZA_IMAGE"], "python", "-c", code))
    run(command)


def own_volume(values):
    volume_command(values, """import os
os.chown('/data',10001,10001)
for root, directories, files in os.walk('/data',followlinks=False):
    for name in directories+files:
        os.lchown(os.path.join(root,name),10001,10001)
""", chown=True)


def healthy(values, *, wait=120):
    deadline = time.monotonic() + wait
    while True:
        try:
            with urllib.request.urlopen("http://127.0.0.1:" + values["LISTEN_PORT"] + "/api/health", timeout=3) as response:
                result = json.load(response)
            if result.get("status") == "ok" and result.get("version") == values["VERSION"]:
                return True
        except (OSError, ValueError):
            pass
        if time.monotonic() >= deadline:
            return False
        time.sleep(1)


def diagnostics(directory):
    compose(directory, "ps")
    compose(directory, "logs", "--tail", "100", "api")


def point_current(directory):
    pending = ROOT / ".current-next"
    pending.unlink(missing_ok=True)
    pending.symlink_to(Path(directory), target_is_directory=True)
    pending.replace(ROOT / "current")


def record_install(values):
    atomic_write(ROOT / "installed.json", json.dumps(dict(version=values["VERSION"], port=values["LISTEN_PORT"],
                 volume=values["DATA_VOLUME"])))


def start(directory, values):
    compose(directory, "up", "-d")
    if not healthy(values):
        diagnostics(directory)
        raise RuntimeError("Service failed bounded loopback health/version verification")
    record_install(values)


def install(values, directory):
    prerequisites()
    check_port(values)
    run(["docker", "pull", values["PREZA_IMAGE"]])
    runtime_files(values)
    compose(directory, "config", "--quiet")
    own_volume(values)
    start(directory, values)
    print("Preza is healthy on loopback:", values["LISTEN_PORT"])
    print("Server-managed Nginx vhost:", directory / "nginx/preza.conf")


def backup_data(values):
    backup = ROOT / "backups" / (time.strftime("%Y%m%dT%H%M%SZ", time.gmtime()) + "-" + secrets.token_hex(3))
    backup.mkdir(parents=True, mode=0o700)
    volume_command(values, """import tarfile
with tarfile.open('/backup/data.tar.gz','w:gz') as archive:
    archive.add('/data',arcname='data',filter=lambda item: None if '/.staging' in item.name else item)
""", backup=backup, readonly=True)
    return backup


def restore_data(values, backup):
    volume_command(values, """import os,tarfile,shutil
from pathlib import Path,PurePosixPath
root=Path('/data')
with tarfile.open('/backup/data.tar.gz','r:gz') as archive:
    members=archive.getmembers()
    for member in members:
        path=PurePosixPath(member.name)
        if path.is_absolute() or '..' in path.parts or not path.parts or path.parts[0]!='data' or not (member.isfile() or member.isdir()):
            raise RuntimeError('Unsafe backup')
    for entry in root.iterdir():
        if entry.is_symlink() or entry.is_file(): entry.unlink()
        else: shutil.rmtree(entry)
    for member in members:
        target=root.joinpath(*PurePosixPath(member.name).parts[1:])
        if member.isdir(): target.mkdir(parents=True,exist_ok=True)
        else:
            target.parent.mkdir(parents=True,exist_ok=True)
            with archive.extractfile(member) as source,target.open('wb') as out: shutil.copyfileobj(source,out)
        os.chown(target,10001,10001)
""", backup=backup, chown=True)


def rollback(values, journal):
    if journal.get("volume") != values["DATA_VOLUME"]:
        raise RuntimeError("Rollback belongs to a different data volume. Restore the original DATA_VOLUME first.")
    previous = ROOT / "releases" / validate_version(journal["previous_version"])
    backup = Path(journal["backup"])
    if backup.parent.resolve() != (ROOT / "backups").resolve() or not (backup / "data.tar.gz").is_file():
        raise RuntimeError("Rollback backup is missing or outside this service")
    release = manifest(previous)
    compose(ROOT / "current", "stop", "api")
    previous_values = release_locks(values, release, previous)
    restore_data(previous_values, backup)
    write_env(previous_values)
    runtime_files(previous_values)
    point_current(previous)
    start(previous, previous_values)
    (ROOT / "update-pending.json").unlink(missing_ok=True)
    print("Restored healthy previous version:", previous_values["VERSION"])


def update(values, directory, version):
    validate_version(version)
    if version == values["VERSION"]:
        raise RuntimeError("This version is already installed")
    prerequisites()
    if not (ROOT / "installed.json").exists() or not healthy(values, wait=0):
        raise RuntimeError("The current service must be healthy before updating")
    target = ROOT / "releases" / version
    if target.exists():
        # Reuse only an already authenticated immutable release.
        release = manifest(target)
    else:
        with tempfile.TemporaryDirectory(prefix=".update-", dir=ROOT) as scratch:
            extracted, release = fetch_release(version, TRUST, Path(scratch) / "bundle")
            shutil.move(str(extracted), target)
    candidate = release_locks(values, release, target)
    run(["docker", "pull", candidate["PREZA_IMAGE"]])
    runtime_files(candidate)
    try:
        compose(target, "config", "--quiet")
    except BaseException:
        runtime_files(values)
        raise
    compose(directory, "stop", "api")
    try:
        backup = backup_data(values)
    except BaseException:
        runtime_files(values)
        start(directory, values)
        raise
    journal = dict(previous_version=values["VERSION"], target_version=version,
                   volume=values["DATA_VOLUME"], backup=str(backup))
    atomic_write(ROOT / "update-pending.json", json.dumps(journal))
    try:
        write_env(candidate)
        point_current(target)
        start(target, candidate)
    except BaseException:
        print("Update failed; restoring the previous release and its data.", file=sys.stderr)
        rollback(values, journal)
        raise
    atomic_write(ROOT / "previous-update.json", json.dumps(journal))
    (ROOT / "update-pending.json").unlink(missing_ok=True)
    print("Verified update complete:", version)
    print("Data backup:", backup / "data.tar.gz")
    print("Nginx was not changed or reloaded.")


def main():
    if os.geteuid() != 0:
        raise RuntimeError("Run preza-install with sudo")
    command = sys.argv[1] if len(sys.argv) > 1 else "install"
    if command == "prepare":
        prepare()
        return
    supported_host()
    with (ROOT / ".installer.lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        path = ROOT / ".env"
        if path.is_symlink() or path.stat().st_uid != 0 or path.stat().st_mode & 0o077:
            raise RuntimeError("Service .env must be root-owned and mode 0600")
        values = load_env(path)
        directory = (ROOT / "current").resolve()
        release = manifest(directory)
        if command == "rollback":
            journal_path = ROOT / "update-pending.json"
            if not journal_path.exists():
                journal_path = ROOT / "previous-update.json"
            rollback(values, json.loads(journal_path.read_text()))
            (ROOT / "previous-update.json").unlink(missing_ok=True)
            return
        if (ROOT / "update-pending.json").exists():
            raise RuntimeError("Interrupted update detected. Run preza-install rollback.")
        if (ROOT / "installed.json").exists():
            installed = json.loads((ROOT / "installed.json").read_text())
            if installed["volume"] != values.get("DATA_VOLUME"):
                raise RuntimeError("DATA_VOLUME cannot change after installation without explicit data migration")
        validate_config(values, release, directory)
        if command == "install":
            install(values, directory)
        elif command == "status":
            compose(directory, "ps")
            if not healthy(values, wait=0):
                raise RuntimeError("Preza is not healthy")
            print("Healthy version:", values["VERSION"])
        elif command == "update" and len(sys.argv) == 3:
            update(values, directory, sys.argv[2])
        else:
            raise RuntimeError("Usage: preza-install [install|status|update VERSION|rollback]")


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        raise SystemExit("Preza installer failed: " + str(error))
